export const AddTodo = '[TODO] Add'
export const RemoveTodo = '[TODO] Remove'
export const EditTodo = '[TODO] Edit'
export const setEdit = '[TODO] Editing'
export const ToggleTodo = '[TODO] Toggle'
export const StarredTodo = '[TODO] Starred'
